var config_e17n52_creeps_transportCreep = {
    storageViaSrcOneContainer: {
        creepOrigin: null,
        creepDestination: Game.rooms['E17N53'].storage,
        creepParts: [
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
        ],
        creepResourceType: RESOURCE_ENERGY,
    },
}

module.exports = config_e17n52_creeps_transportCreep
