var config_e16n54_creeps_transportCreep = {
    storageViaSrcOneContainer: {
        creepOrigin: Game.getObjectById('') || { id: null },
        creepDestination: Game.rooms['E17N53'].storage,
        creepParts: [
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
        ],
        creepResourceType: RESOURCE_ENERGY,
    },
}

module.exports = config_e16n54_creeps_transportCreep
