var config_e18n55_creeps_transportCreep = {
    storageViaSrcOneContainer: {
        creepOrigin: Game.getObjectById('60952efa59886de547babcee') || {
            id: null,
        },
        creepDestination: Game.rooms['E17N55'].storage,
        creepParts: [
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            MOVE,
            WORK,
            WORK,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
            CARRY,
        ],
        creepResourceType: RESOURCE_ENERGY,
    },
}

module.exports = config_e18n55_creeps_transportCreep
