routines_e17n53_buildCreeps_buildCreep = require('routines_e17n53_buildCreeps_buildCreep')
routines_e17n53_claimCreeps_claimCreep = require('routines_e17n53_claimCreeps_claimCreep')
routines_e17n54_claimCreeps_claimCreep = require('routines_e17n54_claimCreeps_claimCreep')
routines_e17n56_claimCreeps_claimCreep = require('routines_e17n56_claimCreeps_claimCreep')
routines_e18n55_claimCreeps_claimCreep = require('routines_e18n55_claimCreeps_claimCreep')
routines_e17n53_upgradeCreeps_upgradeCreep = require('routines_e17n53_upgradeCreeps_upgradeCreep')
routines_e17n54_buildCreeps_buildCreep = require('routines_e17n54_buildCreeps_buildCreep')
routines_e16n55_buildCreeps_buildCreep = require('routines_e16n55_buildCreeps_buildCreep')
routines_e16n55_warriorCreeps_warriorCreep = require('routines_e16n55_warriorCreeps_warriorCreep')
//routines_e16n55_snipeCreeps_snipeCreep = require('routines_e16n55_snipeCreeps_snipeCreep')
routines_e17n54_scoutCreeps_scoutCreep = require('routines_e17n54_scoutCreeps_scoutCreep')
routines_e17n56_scoutCreeps_scoutCreep = require('routines_e17n56_scoutCreeps_scoutCreep')
routines_e17n56_feederCreeps_feederCreep = require('routines_e17n56_feederCreeps_feederCreep')
routines_e17n56_upgradeCreeps_upgradeCreep = require('routines_e17n56_upgradeCreeps_upgradeCreep')
routines_e17n56_sourceCreeps_srcOne = require('routines_e17n56_sourceCreeps_srcOne')
routines_e16n55_scoutCreeps_scoutCreep = require('routines_e16n55_scoutCreeps_scoutCreep')
routines_e16n54_scoutCreeps_scoutCreep = require('routines_e16n54_scoutCreeps_scoutCreep')
routines_e16n54_utriumCreeps_utriumCreep = require('routines_e16n54_utriumCreeps_utriumCreep')
routines_e17n54_sourceCreeps_srcOne = require('routines_e17n54_sourceCreeps_srcOne')
routines_e18n55_sourceCreeps_srcOne = require('routines_e18n55_sourceCreeps_srcOne')
routines_e17n55_upgradeCreeps_upgradeCreep = require('routines_e17n55_upgradeCreeps_upgradeCreep')
routines_e17n55_buildCreeps_buildCreep = require('routines_e17n55_buildCreeps_buildCreep')
routines_e17n56_buildCreeps_buildCreep = require('routines_e17n56_buildCreeps_buildCreep')
routines_e17n55_lootCreeps_lootCreep = require('routines_e17n55_lootCreeps_lootCreep')
routines_e17n53_lootCreeps_lootCreep = require('routines_e17n53_lootCreeps_lootCreep')
routines_e17n55_feederCreeps_feederCreep = require('routines_e17n55_feederCreeps_feederCreep')
routines_e17n55_transportCreeps_linkViaStorage = require('routines_e17n55_transportCreeps_linkViaStorage')
routines_e17n55_transportCreeps_spawnerViaStorage = require('routines_e17n55_transportCreeps_spawnerViaStorage')
routines_e17n55_transportCreeps_storageViaSrcTwoContainer = require('routines_e17n55_transportCreeps_storageViaSrcTwoContainer')
routines_e17n55_transportCreeps_storageViaUtriumContainer = require('routines_e17n55_transportCreeps_storageViaUtriumContainer')
routines_e17n55_transportCreeps_labViaUtriumContainer = require('routines_e17n55_transportCreeps_labViaUtriumContainer')
routines_e17n53_feederCreeps_feederCreep = require('routines_e17n53_feederCreeps_feederCreep')
routines_e17n53_sourceCreeps_srcOne = require('routines_e17n53_sourceCreeps_srcOne')
routines_e17n55_sourceCreeps_srcOne = require('routines_e17n55_sourceCreeps_srcOne')
routines_e16n55_sourceCreeps_srcOne = require('routines_e16n55_sourceCreeps_srcOne')
routines_e17n55_sourceCreeps_srcTwo = require('routines_e17n55_sourceCreeps_srcTwo')
routines_e17n55_towers_towerOne = require('routines_e17n55_towers_towerOne')
routines_e17n55_towers_towerTwo = require('routines_e17n55_towers_towerTwo')
routines_e17n53_towers_towerOne = require('routines_e17n53_towers_towerOne')
routines_e17n55_labs_lab6 = require('routines_e17n55_labs_lab6')
routines_e18n55_scoutCreeps_scoutCreep = require('routines_e18n55_scoutCreeps_scoutCreep')
routines_e18n55_claimCreeps_claimCreep = require('routines_e18n55_claimCreeps_claimCreep')
routines_e17n55_links_spawnLink_via_storageLink = require('routines_e17n55_links_spawnLink_via_storageLink')
routines_e17n55_hydrogenCreeps_hydrogenCreep = require('routines_e17n55_hydrogenCreeps_hydrogenCreep')

utils_garbageCollection_gc = require('utils_garbageCollection_gc')

module.exports.loop = function () {
    if ( Game.cpu.bucket > 9999 ) {
        Game.cpu.generatePixel()
    }

    routines_e17n55_transportCreeps_linkViaStorage.run()
    routines_e17n55_transportCreeps_spawnerViaStorage.run()
    routines_e17n55_transportCreeps_storageViaSrcTwoContainer.run()
    routines_e17n55_transportCreeps_storageViaUtriumContainer.run()
    routines_e17n55_transportCreeps_labViaUtriumContainer.run()
    routines_e17n55_feederCreeps_feederCreep.run()
    routines_e16n55_sourceCreeps_srcOne.run()
    routines_e17n55_sourceCreeps_srcOne.run()
    routines_e17n55_sourceCreeps_srcTwo.run()
    routines_e17n53_sourceCreeps_srcOne.run()
    routines_e17n53_buildCreeps_buildCreep.run()
    routines_e17n53_claimCreeps_claimCreep.run()
    routines_e17n54_claimCreeps_claimCreep.run()
    routines_e17n56_claimCreeps_claimCreep.run()
    routines_e18n55_claimCreeps_claimCreep.run()
    //routines_e17n54_buildCreeps_buildCreep.run()
    routines_e16n55_buildCreeps_buildCreep.run()
    routines_e16n55_warriorCreeps_warriorCreep.run()
    routines_e17n54_sourceCreeps_srcOne.run()
    routines_e18n55_sourceCreeps_srcOne.run()
    routines_e17n54_scoutCreeps_scoutCreep.run()
    routines_e17n56_scoutCreeps_scoutCreep.run()
    routines_e17n56_feederCreeps_feederCreep.run()
    routines_e17n56_upgradeCreeps_upgradeCreep.run()
    routines_e17n56_sourceCreeps_srcOne.run()
    routines_e16n55_scoutCreeps_scoutCreep.run()
    routines_e16n54_scoutCreeps_scoutCreep.run()
    routines_e16n54_utriumCreeps_utriumCreep.run()
    routines_e17n55_upgradeCreeps_upgradeCreep.run()
    routines_e17n53_upgradeCreeps_upgradeCreep.run()
    routines_e17n53_feederCreeps_feederCreep.run()
    routines_e17n55_buildCreeps_buildCreep.run()
    routines_e17n56_buildCreeps_buildCreep.run()
    routines_e17n55_lootCreeps_lootCreep.run()
    routines_e17n53_lootCreeps_lootCreep.run()
    routines_e17n55_towers_towerOne.run()
    routines_e17n55_towers_towerTwo.run()
    routines_e17n53_towers_towerOne.run()
    routines_e18n55_scoutCreeps_scoutCreep.run()
    routines_e18n55_claimCreeps_claimCreep.run()
    routines_e17n55_links_spawnLink_via_storageLink.run()
    //routines_e16n55_snipeCreeps_snipeCreep.run()
    utils_garbageCollection_gc.garbageCollection.creeps.run()
    routines_e17n55_hydrogenCreeps_hydrogenCreep.run()
    routines_e17n55_labs_lab6.run()
}