routines_e17n53_buildCreeps_buildCreep = require('routines_e17n53_buildCreeps_buildCreep')
routines_e17n53_claimCreeps_claimCreep = require('routines_e17n53_claimCreeps_claimCreep')
routines_e17n54_claimCreeps_claimCreep = require('routines_e17n54_claimCreeps_claimCreep')
routines_e17n56_claimCreeps_claimCreep = require('routines_e17n56_claimCreeps_claimCreep')
routines_e18n55_claimCreeps_claimCreep = require('routines_e18n55_claimCreeps_claimCreep')
routines_e17n53_upgradeCreeps_upgradeCreep = require('routines_e17n53_upgradeCreeps_upgradeCreep')
routines_e17n54_buildCreeps_buildCreep = require('routines_e17n54_buildCreeps_buildCreep')
routines_e16n55_buildCreeps_buildCreep = require('routines_e16n55_buildCreeps_buildCreep')
routines_e16n55_warriorCreeps_warriorCreep = require('routines_e16n55_warriorCreeps_warriorCreep')
routines_e16n55_snipeCreeps_snipeCreep = require('routines_e16n55_snipeCreeps_snipeCreep')
routines_e17n54_warriorCreeps_warriorCreep = require('routines_e17n54_warriorCreeps_warriorCreep')
routines_e18n55_warriorCreeps_warriorCreep = require('routines_e18n55_warriorCreeps_warriorCreep')
routines_e16n55_healerCreeps_healerCreep = require('routines_e16n55_healerCreeps_healerCreep')
//routines_e16n55_snipeCreeps_snipeCreep = require('routines_e16n55_snipeCreeps_snipeCreep');
routines_e17n54_scoutCreeps_scoutCreep = require('routines_e17n54_scoutCreeps_scoutCreep')
routines_e17n56_scoutCreeps_scoutCreep = require('routines_e17n56_scoutCreeps_scoutCreep')
routines_e17n56_feederCreeps_feederCreep = require('routines_e17n56_feederCreeps_feederCreep')
routines_e17n56_upgradeCreeps_upgradeCreep = require('routines_e17n56_upgradeCreeps_upgradeCreep')
routines_e17n56_sourceCreeps_srcOne = require('routines_e17n56_sourceCreeps_srcOne')
routines_e17n56_sourceCreeps_srcTwo = require('routines_e17n56_sourceCreeps_srcTwo')
routines_e16n54_scoutCreeps_scoutCreep = require('routines_e16n54_scoutCreeps_scoutCreep')
routines_e16n55_scoutCreeps_scoutCreep = require('routines_e16n55_scoutCreeps_scoutCreep')
routines_e16n55_oxygenCreeps_oxygenCreep = require('routines_e16n55_oxygenCreeps_oxygenCreep')
routines_e16n54_utriumCreeps_utriumCreep = require('routines_e16n54_utriumCreeps_utriumCreep')
routines_e17n54_sourceCreeps_srcOne = require('routines_e17n54_sourceCreeps_srcOne')
routines_e16n54_sourceCreeps_srcOne = require('routines_e16n54_sourceCreeps_srcOne')
routines_e18n55_sourceCreeps_srcOne = require('routines_e18n55_sourceCreeps_srcOne')
routines_e17n55_upgradeCreeps_upgradeCreep = require('routines_e17n55_upgradeCreeps_upgradeCreep')
routines_e17n55_buildCreeps_buildCreep = require('routines_e17n55_buildCreeps_buildCreep')
routines_e17n52_buildCreeps_buildCreep = require('routines_e17n52_buildCreeps_buildCreep')
routines_e17n56_buildCreeps_buildCreep = require('routines_e17n56_buildCreeps_buildCreep')
routines_e17n55_lootCreeps_lootCreep = require('routines_e17n55_lootCreeps_lootCreep')
routines_e17n56_lootCreeps_lootCreep = require('routines_e17n56_lootCreeps_lootCreep')
routines_e18n55_lootCreeps_lootCreep = require('routines_e18n55_lootCreeps_lootCreep')
routines_e17n54_lootCreeps_lootCreep = require('routines_e17n54_lootCreeps_lootCreep')
routines_e16n54_lootCreeps_lootCreep = require('routines_e16n54_lootCreeps_lootCreep')
routines_e16n55_lootCreeps_lootCreep = require('routines_e16n55_lootCreeps_lootCreep')
routines_e17n53_lootCreeps_lootCreep = require('routines_e17n53_lootCreeps_lootCreep')
routines_e15n53_lootCreeps_lootCreep = require('routines_e15n53_lootCreeps_lootCreep')
routines_e17n55_feederCreeps_feederCreep = require('routines_e17n55_feederCreeps_feederCreep')
routines_e17n55_transportCreeps_linkViaStorage = require('routines_e17n55_transportCreeps_linkViaStorage')
routines_e17n55_transportCreeps_spawnerViaStorage = require('routines_e17n55_transportCreeps_spawnerViaStorage')
routines_e17n55_transportCreeps_storageViaSrcTwoContainer = require('routines_e17n55_transportCreeps_storageViaSrcTwoContainer')
routines_e17n56_transportCreeps_storageViaSrcOneContainer = require('routines_e17n56_transportCreeps_storageViaSrcOneContainer')
routines_e17n54_transportCreeps_storageViaSrcOneContainer = require('routines_e17n54_transportCreeps_storageViaSrcOneContainer')
routines_e18n55_transportCreeps_storageViaSrcOneContainer = require('routines_e18n55_transportCreeps_storageViaSrcOneContainer')
routines_e17n56_transportCreeps_storageViaSrcTwoContainer = require('routines_e17n56_transportCreeps_storageViaSrcTwoContainer')
routines_e17n55_transportCreeps_storageViaUtriumContainer = require('routines_e17n55_transportCreeps_storageViaUtriumContainer')
routines_e17n55_transportCreeps_labViaUtriumContainer = require('routines_e17n55_transportCreeps_labViaUtriumContainer')
routines_e17n53_feederCreeps_feederCreep = require('routines_e17n53_feederCreeps_feederCreep')
routines_e17n52_sourceCreeps_srcOne = require('routines_e17n52_sourceCreeps_srcOne')
routines_e17n53_sourceCreeps_srcOne = require('routines_e17n53_sourceCreeps_srcOne')
routines_e17n55_sourceCreeps_srcOne = require('routines_e17n55_sourceCreeps_srcOne')
routines_e16n55_sourceCreeps_srcOne = require('routines_e16n55_sourceCreeps_srcOne')
routines_e17n55_sourceCreeps_srcTwo = require('routines_e17n55_sourceCreeps_srcTwo')
routines_e17n56_towers_towerOne = require('routines_e17n56_towers_towerOne')
routines_e17n55_towers_towerOne = require('routines_e17n55_towers_towerOne')
routines_e17n55_towers_towerTwo = require('routines_e17n55_towers_towerTwo')
routines_e17n53_towers_towerOne = require('routines_e17n53_towers_towerOne')
routines_e17n55_labs_lab6 = require('routines_e17n55_labs_lab6')
routines_e18n55_scoutCreeps_scoutCreep = require('routines_e18n55_scoutCreeps_scoutCreep')
routines_e18n55_claimCreeps_claimCreep = require('routines_e18n55_claimCreeps_claimCreep')
routines_e17n55_links_spawnLink_via_storageLink = require('routines_e17n55_links_spawnLink_via_storageLink')
routines_e17n55_hydrogenCreeps_hydrogenCreep = require('routines_e17n55_hydrogenCreeps_hydrogenCreep')
routines_e17n53_keaniumCreeps_keaniumCreep = require('routines_e17n53_keaniumCreeps_keaniumCreep')
routines_e17n53_transportCreeps_terminalViaStorage = require('routines_e17n53_transportCreeps_terminalViaStorage')
routines_e17n55_transportCreeps_labViaStorage = require('routines_e17n55_transportCreeps_labViaStorage')
routines_e16n54_srcKeeperCreeps_utriumKeeper = require('routines_e16n54_srcKeeperCreeps_utriumKeeper')
routines_e17n53_towers_towerTwo = require('routines_e17n53_towers_towerTwo')
routines_e15n53_towers_towerTwo = require('routines_e15n53_towers_towerTwo')
routines_e17n55_towers_towerThree = require('routines_e17n55_towers_towerThree')
routines_e16n54_srcKeeperCreeps_sourceOneKeeper = require('routines_e16n54_srcKeeperCreeps_sourceOneKeeper')
routines_e16n55_srcKeeperCreeps_sourceOneKeeper = require('routines_e16n55_srcKeeperCreeps_sourceOneKeeper')
routines_e16n55_sourceCreeps_srcOne = require('routines_e16n55_sourceCreeps_srcOne')
routines_e16n55_sourceCreeps_srcTwo = require('routines_e16n55_sourceCreeps_srcTwo')
routines_e15n53_claimCreeps_claimCreep = require('routines_e15n53_claimCreeps_claimCreep')
routines_e17n52_claimCreeps_claimCreep = require('routines_e17n52_claimCreeps_claimCreep')
routines_e17n53_transportCreeps_e17n55StorageviaStorage = require('routines_e17n53_transportCreeps_e17n55StorageviaStorage')
routines_e17n56_links_storage_via_srcTwo = require('routines_e17n56_links_storage_via_srcTwo')
routines_e17n56_transportCreeps_upgradeContainerviaStorage = require('routines_e17n56_transportCreeps_upgradeContainerviaStorage')
routines_e15n53_buildCreeps_buildCreep = require('routines_e15n53_buildCreeps_buildCreep')
routines_e15n53_upgradeCreeps_upgradeCreep = require('routines_e15n53_upgradeCreeps_upgradeCreep')
routines_e15n53_sourceCreeps_srcOne = require('routines_e15n53_sourceCreeps_srcOne')
routines_e15n53_feederCreeps_feederCreep = require('routines_e15n53_feederCreeps_feederCreep')
routines_e20n49_mistCreeps_srcOne = require('routines_e20n49_mistCreeps_srcOne')
routines_e17n56_towers_towerTwo = require('routines_e17n56_towers_towerTwo')
routines_e17n56_hydrogenCreeps_hydrogenCreep = require('routines_e17n56_hydrogenCreeps_hydrogenCreep')
utils_garbageCollection_gc = require('utils_garbageCollection_gc')
routines_e16n55_buildCreeps_buildCreep = require('routines_e16n55_buildCreeps_buildCreep')
routines_e18n55_buildCreeps_buildCreep = require('routines_e18n55_buildCreeps_buildCreep')
routines_e16n55_transportCreeps_srcOneToE17N55Storage = require('routines_e16n55_transportCreeps_srcOneToE17N55Storage')
respawn_e17n55_routine = require('respawn_e17n55_routine')
routines_e16n53_warriorCreeps_warriorCreep = require('routines_e16n53_warriorCreeps_warriorCreep')
routines_e16n53_sourceCreeps_srcOne = require('routines_e16n53_sourceCreeps_srcOne')
routines_e16n53_sourceCreeps_srcTwo = require('routines_e16n53_sourceCreeps_srcTwo')
routines_e16n53_claimCreeps_claimCreep = require('routines_e16n53_claimCreeps_claimCreep')

timerReport = 600

module.exports.loop = function () {
    if (Game.cpu.bucket > 9999) {
        Game.cpu.generatePixel()
    }

    // if(timerReport == 600){
    //     for(creep in Game.creeps){
    //         console.log(Game.creeps[creep].name + ' Lifetime: ' + (Game.creeps[creep].ticksToLive*2.75)/60 + '/'+ (1500*2.75)/60)
    //     }
    //     timerReport = 0
    // }
    // timerReport = timerReport + 1

    routines_e17n55_transportCreeps_linkViaStorage.run()
    routines_e17n55_transportCreeps_spawnerViaStorage.run()
    routines_e17n55_transportCreeps_storageViaSrcTwoContainer.run()
    routines_e17n56_transportCreeps_storageViaSrcOneContainer.run()
    routines_e17n56_transportCreeps_storageViaSrcTwoContainer.run()
    routines_e17n55_transportCreeps_storageViaUtriumContainer.run()
    routines_e17n55_transportCreeps_labViaUtriumContainer.run()
    routines_e17n55_feederCreeps_feederCreep.run()
    routines_e16n55_sourceCreeps_srcOne.run()
    routines_e17n55_sourceCreeps_srcOne.run()
    routines_e17n55_sourceCreeps_srcTwo.run()
    routines_e17n53_sourceCreeps_srcOne.run()
    routines_e17n52_sourceCreeps_srcOne.run()
    routines_e17n53_buildCreeps_buildCreep.run()
    routines_e17n53_claimCreeps_claimCreep.run()
    routines_e17n54_claimCreeps_claimCreep.run()
    routines_e17n56_claimCreeps_claimCreep.run()
    routines_e18n55_claimCreeps_claimCreep.run()
    routines_e17n54_buildCreeps_buildCreep.run()
    routines_e16n55_buildCreeps_buildCreep.run()
    routines_e18n55_buildCreeps_buildCreep.run()
    routines_e17n52_buildCreeps_buildCreep.run()
    routines_e16n55_warriorCreeps_warriorCreep.run()
    routines_e16n55_healerCreeps_healerCreep.run()
    routines_e16n54_sourceCreeps_srcOne.run()
    routines_e17n54_sourceCreeps_srcOne.run()
    routines_e18n55_sourceCreeps_srcOne.run()
    routines_e17n54_scoutCreeps_scoutCreep.run()
    routines_e17n56_scoutCreeps_scoutCreep.run()
    routines_e17n56_feederCreeps_feederCreep.run()
    routines_e17n56_upgradeCreeps_upgradeCreep.run()
    routines_e17n56_sourceCreeps_srcOne.run()
    routines_e17n56_sourceCreeps_srcTwo.run()
    routines_e16n55_scoutCreeps_scoutCreep.run()
    routines_e16n55_oxygenCreeps_oxygenCreep.run()
    routines_e16n54_scoutCreeps_scoutCreep.run()
    routines_e16n54_utriumCreeps_utriumCreep.run()
    routines_e17n55_upgradeCreeps_upgradeCreep.run()
    routines_e17n53_upgradeCreeps_upgradeCreep.run()
    routines_e17n53_feederCreeps_feederCreep.run()
    routines_e17n55_buildCreeps_buildCreep.run()
    routines_e17n56_buildCreeps_buildCreep.run()
    routines_e17n55_lootCreeps_lootCreep.run()
    routines_e17n56_lootCreeps_lootCreep.run()
    routines_e17n54_lootCreeps_lootCreep.run()
    routines_e18n55_lootCreeps_lootCreep.run()
    routines_e16n54_lootCreeps_lootCreep.run()
    routines_e16n55_lootCreeps_lootCreep.run()
    routines_e17n53_lootCreeps_lootCreep.run()
    routines_e15n53_lootCreeps_lootCreep.run()
    routines_e17n55_towers_towerOne.run()
    routines_e17n56_towers_towerOne.run()
    routines_e17n55_towers_towerTwo.run()
    routines_e17n55_towers_towerThree.run()
    routines_e17n53_towers_towerOne.run()
    routines_e18n55_scoutCreeps_scoutCreep.run()
    routines_e18n55_claimCreeps_claimCreep.run()
    routines_e17n55_links_spawnLink_via_storageLink.run()
    routines_e16n55_snipeCreeps_snipeCreep.run()
    utils_garbageCollection_gc.garbageCollection.creeps.run()
    routines_e17n55_hydrogenCreeps_hydrogenCreep.run()
    // routines_e17n55_labs_lab6.run();
    routines_e18n55_warriorCreeps_warriorCreep.run()
    routines_e17n54_warriorCreeps_warriorCreep.run()
    routines_e17n53_keaniumCreeps_keaniumCreep.run()
    routines_e17n53_transportCreeps_terminalViaStorage.run()
    routines_e17n55_transportCreeps_labViaStorage.run()
    routines_e16n54_srcKeeperCreeps_utriumKeeper.run()
    routines_e16n54_srcKeeperCreeps_sourceOneKeeper.run()
    routines_e16n55_srcKeeperCreeps_sourceOneKeeper.run()
    routines_e17n55_towers_towerTwo.run()
    routines_e16n55_sourceCreeps_srcOne.run()
    routines_e16n55_buildCreeps_buildCreep.run()
    routines_e16n55_sourceCreeps_srcTwo.run()
    routines_e15n53_claimCreeps_claimCreep.run()
    routines_e17n52_claimCreeps_claimCreep.run()
    routines_e17n54_transportCreeps_storageViaSrcOneContainer.run()
    routines_e18n55_transportCreeps_storageViaSrcOneContainer.run()
    routines_e17n53_transportCreeps_e17n55StorageviaStorage.run()
    routines_e17n56_links_storage_via_srcTwo.run()
    routines_e17n56_transportCreeps_upgradeContainerviaStorage.run()
    routines_e15n53_buildCreeps_buildCreep.run()
    routines_e15n53_upgradeCreeps_upgradeCreep.run()
    routines_e15n53_sourceCreeps_srcOne.run()
    routines_e15n53_feederCreeps_feederCreep.run()
    routines_e20n49_mistCreeps_srcOne.run()
    routines_e17n56_towers_towerTwo.run()
    routines_e17n56_hydrogenCreeps_hydrogenCreep.run()
    routines_e17n53_towers_towerTwo.run()
    routines_e17n56_towers_towerTwo.run()
    routines_e15n53_towers_towerTwo.run()
    routines_e16n55_transportCreeps_srcOneToE17N55Storage.run()
    routines_e16n53_warriorCreeps_warriorCreep.run()
    routines_e16n53_claimCreeps_claimCreep.run()
    routines_e16n53_sourceCreeps_srcOne.run()
    routines_e16n53_sourceCreeps_srcTwo.run()
}
